version: "3.8"
services:
  postgres:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgres/dumps/:/tmp/
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: "sql"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always

volumes:
  database:
    driver: local